version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: atom-dbro-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-atom_dbro}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atom-internal-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atom-dbro-app
    ports:
      - "3000:3000"
    env_file:
      - .env  # Загружаем переменные из .env файла
    environment:
      PORT: ${PORT:-3000}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-atom_dbro}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./drizzle:/app/drizzle
    networks:
      - atom-external-network
      - atom-internal-network

volumes:
  postgres_data:

networks:
  atom-external-network:
    driver: bridge
  atom-internal-network:
    driver: bridge
  